stages:
  - build
  - deploy

  

before_script:
  - echo "${T007_DOCKER_HUB_TOKEN}" | docker login -u "${T007_REGISTRY_USER_NAME}" --password-stdin

services:
  - name: docker:dind

build:
  stage: build
  image: docker:latest
  script:
    - chmod +x ./applications/launch.sh
    - sh ./applications/launch.sh
    - docker images
    - mkdir images
    - docker save ${T007_REGISTRY_USER_NAME}/t-007-qr > images/t-007-qr.tar
    - docker save ${T007_REGISTRY_USER_NAME}/t-007-backend > images/t-007-backend.tar
    - docker save ${T007_REGISTRY_USER_NAME}/t-007-website > images/t-007-website.tar
  artifacts:
    paths:
      - images/
  tags:
    - t-007

deploy:
  stage: deploy
  script:
    - ls -l images/
    - docker load -i images/t-007-qr.tar
    - docker push "t-007-qr:dev"
    - docker load -i images/t-007-backend.tar
    - docker push "t-007-backend:dev"
    - docker load -i images/t-007-website.tar
    - docker push "t-007-website:dev"
  tags:
    - t-007

