stages:
  - build
  - deploy
  

before_script:
  - echo "${T007_DOCKER_HUB_TOKEN}" | docker login -u "${T007_REGISTRY_USER_NAME}" --password-stdin

services:
  - name: docker:dind

build:
  stage: build
  image: docker:latest
  script:
    - chmod +x ./applications/launch.sh
    - sh ./applications/launch.sh
    - docker ps
    - docker images
qr:
  stage: deploy
  image: docker:latest
  variables:
    image_name: qr
    image_tag: dev
  script:
    - chmod +x ./comp.sh
    - sh ./comp.sh

backend:
  stage: deploy
  variables:
    image_name: backend
    image_tag: dev
  script:
    - chmod +x ./comp.sh
    - sh ./comp.sh

website:
  stage: deploy
  variables:
    image_name: website
    image_tag: dev
  script:
    - chmod +x ./comp.sh
    - sh ./comp.sh
