stages:
  - build

variables:
  WORKING_BRANCH: t-010-dev

build:
  stage: build
  
  image: docker:cli
  
  services:
    - docker:dind
  
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  
  script:
    - cd applications/qr && docker compose up --force-recreate   

  only:
    variables:
      - $WORKING_BRANCH == "t-010-dev"
  tags:
    - t010-build-protected


