stages:
  - build

  

before_script:
  - echo "${T007_DOCKER_HUB_TOKEN}" | docker login -u "${T007_REGISTRY_USER_NAME}" --password-stdin

services:
  - name: docker:dind

build_push:
  stage: build
  image: docker:latest
  script:
    - chmod +x ./applications/launch.sh
    - sh ./applications/launch.sh
