stages:
  - build_push
  - deploy

before_script:
  - echo "$T006_DOCKER_HUB_TOKEN" | docker login -u $T006_REGISTRY_USER_NAME --password-stdin

qr_build_push:
  stage: build_push
  variables:
    image_name : qr
    image_tag: dev
  script:
    - chmod 0755 ./ci-scripts/build_push_images.sh
    - sh ./ci-scripts/build_push_images.sh
  tags:
    - t006-deploy
  only:
    changes:
      - applications/qr/**/*


backend_build_push:
  stage: build_push
  variables:
    image_name : backend
    image_tag: dev
  script:
    - chmod 0755 ./ci-scripts/build_push_images.sh
    - sh ./ci-scripts/build_push_images.sh
  tags:
    - t006-deploy
  only:
    changes:
      - applications/backend/**/*

website_build_push:
  stage: build_push
  variables:
    image_name : website
    image_tag: dev
  script:
    - chmod 0755 ./ci-scripts/build_push_images.sh
    - sh ./ci-scripts/build_push_images.sh
  tags:
    - t006-deploy
  only:
    changes:
      - applications/website/**/*


init_k3d_cluster:
  stage: deploy
  script:
    - chmod 0755 ./training-app-deployment/init-k3d-cluster.sh
    - sh ./training-app-deployment/init-k3d-cluster.sh
  tags:
    - t006-deploy
  only:
    changes:
      - training-app-deployment/init-k3d-cluster.sh
      - training-app-deployment/k3d-config.yml

deploy:
  stage: deploy
  script:
    - chmod 0755 ./training-app-deployment/seal-secrets.sh
    - chmod 0755 ./training-app-deployment/install-k8s-objects.sh
    - sh ./training-app-deployment/install-k8s-objects.sh
  tags:
    - t006-deploy




    