stages:
  - build/deploy

  

before_script:
  - echo "${T007_DOCKER_HUB_TOKEN}" | docker login -u "${T007_REGISTRY_USER_NAME}" --password-stdin

services:
  - name: docker:dind

build_and_deploy:
  stage: build/deploy
  image: docker:latest
  script:
    - chmod +x ./applications/launch.sh
    - sh ./applications/launch.sh
    - docker images
    - docker push "${T007_REGISTRY_USER_NAME}/t-007-qr:dev"
    - docker push "${T007_REGISTRY_USER_NAME}/t-007-backend:dev"
    - docker push "${T007_REGISTRY_USER_NAME}/t-007-website:dev"

