stages:
  - dockerhub_login
  - build
  - push

dockerhub_login:
  stage: dockerhub_login
  script:
    - echo "$T012_DOCKER_HUB_ACCESS_TOKEN" | docker login -u "T012_DOCKER_HUB_USERNAME" --password-stdin
  tags:
    - t012-build-protected

qr_build_jobs:
  stage: build
  script:
    - docker build -t t012-qr:dev ./qr && 
    docker tag t012-qr:dev bramedhedi/t012-qr:dev && 
    docker push bramedhedi/t012-qr:dev   
  tags:
    - t012-build-protected

qr_push_jobs:
  stage: push
  script:
    - docker tag t012-qr:dev bramedhedi/t012-qr:latest && 
    docker push bramedhedi/t012-qr:dev


