stages:
  - CI

before_script:
  - echo "$T001_DOCKER_HUB_TOKEN" | docker login -u "$T001_USERNAME" --password-stdin

qr_build:
  stage: CI
  rules:
    - if: $CI_COMMIT_REF_NAME == "t-001-prod"
      variables:
        IMAGE_TAG: "latest prod"
    - if: $CI_COMMIT_REF_NAME == "t-001-dev"
      variables:
        IMAGE_TAG: "dev"
  script:
    - ./ci-scripts/image-builder.sh
  variables:
    IMAGE_NAME : "qr"

website_build:
  stage: CI
  rules:
    - if: $CI_COMMIT_REF_NAME == "t-001-prod"
      variables:
        IMAGE_TAG: "latest prod"
    - if: $CI_COMMIT_REF_NAME == "t-001-dev"
      variables:
        IMAGE_TAG: "dev"
  script:
    - ./ci-scripts/image-builder.sh
  variables:
    IMAGE_NAME : "website"

backend_build:
  stage: CI
  rules:
    - if: $CI_COMMIT_REF_NAME == "t-001-prod"
      variables:
        IMAGE_TAG: "latest prod"
    - if: $CI_COMMIT_REF_NAME == "t-001-dev"
      variables:
        IMAGE_TAG: "dev"
  script:
    - ./ci-scripts/image-builder.sh
  variables:
    IMAGE_NAME : backend