stages:
  - build_push
  - deploy

before_script:
  - echo "$T005_DOCKER_HUB_TOKEN" | docker login -u $T005_REGISTRY_USER_NAME --password-stdin

qr_build_push:
  stage: build_push
  variables:
    image_name : qr
    image_tag: dev
  script:
    - chmod 0755 ./ci-scripts/build_push_images.sh
    - sh ./ci-scripts/build_push_images.sh
  tags:
    - t005-deploy
  only:
    changes:
      - "applications/qr/**/*"

backend_build_push:
  stage: build_push
  variables:
    image_name : backend
    image_tag: dev
  script:
    - chmod 0755 ./ci-scripts/build_push_images.sh
    - sh ./ci-scripts/build_push_images.sh
  tags:
    - t005-deploy
  only:
    changes:
      - "applications/backend/**/*"

website_build_push:
  stage: build_push
  variables:
    image_name : website
    image_tag: dev
  script:
    - chmod 0755 ./ci-scripts/build_push_images.sh
    - sh ./ci-scripts/build_push_images.sh
  tags:
    - t005-deploy
  only:
    changes:
      - "applications/website/**/*"


deploy_applications:
  stage: deploy
  script:
    - chmod 0755 training-app-deployment/subst-variables.sh training-app-deployment/install.sh
    - sh training-app-deployment/subst-variables.sh
    - sh training-app-deployment/install.sh
  tags:
    - t005-deploy
  