stages:
  - build
  - deploy

  

before_script:
  - echo "${T007_DOCKER_HUB_TOKEN}" | docker login -u "${T007_REGISTRY_USER_NAME}" --password-stdin

services:
  - name: docker:dind

build:
  stage: build
  image: docker:latest
  script:
    - chmod +x ./applications/launch.sh
    - sh ./applications/launch.sh
    - docker images

  artifacts:
    paths:
      - app/
  tags:
    - t-007

deploy:
  stage: deploy
  script:
    - ls app
    - docker images
    - docker load -i app/housseinhmila/t-007-qr.tar
    - docker push "${T007_REGISTRY_USER_NAME}/t-007-qr:dev"
    - docker load -i app/housseinhmila/t-007-backend.tar
    - docker push "${T007_REGISTRY_USER_NAME}/t-007-backend:dev"
    - docker load -i app/housseinhmila/t-007-website.tar
    - docker push "${T007_REGISTRY_USER_NAME}/t-007-website:dev"
  tags:
    - t-007

