stages:
  - build

variables:
  
build:
  image: docker:24.0.7


  services:
    - docker:24.0.7-dind
  
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    
  stage: build
  
  script:
    - cd applications && docker compose up -d --force-recreate app_ui
  
  tags:
    - t-nidhal-build-protected
