stages:
  - build
  - push

image: docker:stable

variables:
  SCRIPT_PATH: "./ci-scripts/img_push.sh"

build_website:
  stage: build
  script:
    - docker build -t t013-website:dev ./applications/website
  tags:
    - t-013-deploy
  only:
    - t-013-dev

build_backend:
  stage: build
  script:
    - docker build -t t013-backend:dev ./applications/backend
  tags:
    - t-013-deploy
  only:
    - t-013-dev

build_qr:
  stage: build
  script:
    - docker build -t t013-qr:dev ./applications/qr
  tags:
    - t-013-deploy
  only:
    - t-013-dev

push_website:
  stage: push
  script:
    - sh $SCRIPT_PATH t013-website $T013_REGISTRY_USERNAME $T013_REGISTRY_PASSWORD
  tags:
    - t-013-deploy
  dependencies:
    - build_website
  only:
    - t-013-dev
push_backend:
  stage: push
  script:
    - sh $SCRIPT_PATH t013-backend $T013_REGISTRY_USERNAME $T013_REGISTRY_PASSWORD
  tags:
    - t-013-deploy
  dependencies:
    - build_backend
  only:
    - t-013-dev
push_qr:
  stage: push
  script:
    - sh $SCRIPT_PATH t013-qr $T013_REGISTRY_USERNAME $T013_REGISTRY_PASSWORD
  tags:
    - t-013-deploy
  dependencies:
    - build_qr
  only:
    - t-013-dev
