stages:
  - build_push

before_script:
  - echo "$T005_DOCKER_HUB_TOKEN" | docker login -u $T005_REGISTRY_USER_NAME --password-stdin

qr_build_push:
  stage: build_push
  variables:
    image_name : qr
    image_tag: dev
  script:
    - chmod 0755 ci-scripts/build_push_images.sh
    - ci-scripts/build_push_images.sh
  tags:
    - t005-build


backend_build_push:
  stage: build_push
  variables:
    image_name : backend
    image_tag: dev
  script:
    - chmod 0755 ci-scripts/build_push_images.sh
    - ci-scripts/build_push_images.sh
  tags:
    - t005-build

website_build_push:
  stage: build_push
  variables:
    image_name : website
    image_tag: dev
  script:
    - chmod 0755 ci-scripts/build_push_images.sh
    - ci-scripts/build_push_images.sh
  tags:
    - t005-build