stages:
  - build_push

before_script:
  - echo "$T006_DOCKER_HUB_TOKEN" | docker login -u $T006_REGISTRY_USER_NAME --password-stdin

qr_build_push:
  stage: build_push
  variables:
    image_name : qr
    image_tag: dev
  script:
    - chmod 0755 ci-scripts/build_push_images.sh
    - ci-scripts/build_push_images.sh
  tags:
    - t006-build-protected


backend_build_push:
  stage: build_push
  variables:
    image_name : backend
    image_tag: dev
  script:
    - chmod 0755 ci-scripts/build_push_images.sh
    - ci-scripts/build_push_images.sh
  tags:
    - t006-build-protected

website_build_push:
  stage: build_push
  variables:
    image_name : website
    image_tag: dev
  script:
    - chmod 0755 ci-scripts/build_push_images.sh
    - ci-scripts/build_push_images.sh
  tags:
    - t006-build-protected
