stages:
  - build

variables:
  WORKING_BRANCH: t-010-dev

build:
  stage: build
  
  image: docker:24.0.7
  
  services:
    - docker:24.0.7-dind
  
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  
  script:
    - docker build -t qr:1.0 ./applications/qr     

  only:
    variables:
      - $WORKING_BRANCH == "t-010-dev"
  tags:
    - t010-runner
