stages:
  - build-job


build-job:
  stage: build-job
  image: bitnami/kubectl:latest
  services:
    - docker:dind  
  script:
    - cd kubernetes_deployment
    - chmod 0755 ./create_cluster.sh
    - sh ./create_cluster.sh
    - |
      for secret_file in $(ls secret*.yaml); do
        kubeseal < "${secret_file}" > "${secret_file/.yaml/.sealed.yaml}"
      done      
    - chmod 0755 ./run.sh
    - sh ./run.sh    
    - exit_code=$?
    - if [ $exit_code -eq 0 ]; then echo "Build succeeded !"; else echo "Build failed"; fi
  tags:
    - "t-008-deploy"
