stages:
  - build
  - deploy

image: docker:20.10.16
services:
  - name: docker:20.10.16-dind

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: ""


before_script:
  - docker login -u "${T007_REGISTRY_USER_NAME}" -p "${T007_DOCKER_HUB_TOKEN}"

qr_build:
  stage: build
  variables:
    image_name : qr
    image_tag: dev
  script:
    - echo "Building QR image"
    - docker build -t"${T007_REGISTRY_USER_NAME}/t-007-${image_name}:${image_tag}" applications/${image_name} 
    - echo "finish building QR image"
  tags:
    - t007-build/deploy

backend_build:
  stage: build
  variables:
    image_name : backend
    image_tag: dev
  script:
    - chmod +x ./ci-scripts/comp.sh
    - sh ./ci-scripts/comp.sh
  tags:
    - t007-build/deploy

wabsite_build:
  stage: build
  variables:
    image_name : website
    image_tag: dev
  script:
    - chmod +x ./ci-scripts/comp.sh
    - sh ./ci-scripts/comp.sh
  tags:
    - t007-build/deploy

######################

deploy:
  stage: deploy
  script:
    
    - docker push "${T007_REGISTRY_USER_NAME}/t-007-qr:latest"
    - docker push "${T007_REGISTRY_USER_NAME}/t-007-backend:latest"
    - docker push "${T007_REGISTRY_USER_NAME}/t-007-website:latest"
  tags:
    - t007-build/deploy
