stages:
  - build
  - deploy

build:
  stage: build
  image: bitnami/kubectl:latest
  script:
    - cd training-app-deployment
    - k3d cluster delete devopscluster
    - ./init-k3d-cluster.sh
    - kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.1/deploy/static/provider/cloud/deploy.yaml
    - kubectl apply -f https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.22.0/controller.yaml
    - kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=-1s
      
  tags:
    - t-007-dev

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - kubectl apply -k .
    - ./seals.sh
    - ./rm *secret.yml
  
  tags:
    - t-007-dev



