stages:
  - build-job

build-job:
  stage: build-job
  image: docker:latest
  services:
    - docker:dind  
  script:
    - docker compose -f ./applications/docker-compose-B.yaml up
    - echo "builded successfully"
  tags:
    - "t-008-deploy"  


