stages:
  - build-job

before_script:
  - echo "${T008_DOCKER_HUB_TOKEN}" | docker login -u "${T008_REGISTRY_USER_NAME}" --password-stdin


build-job:
  stage: build-job
  image: docker:latest
  services:
    - docker:dind  
  script:
    - docker compose -f ./applications/docker-compose-B.yaml up
    - echo "builded successfully"
  tags:
    - "t-008-deploy"  


