stages:
  - build-job


build-job:
  stage: build-job
  image: bitnami/kubectl:latest
  services:
    - docker:dind  
  script:
    - cd kubernetes_deployment
    - chmod 0755 ./create_cluster.sh
    - ./create_cluster.sh
    - chmod 0755 ./sealedSecret.sh
    - ./sealedSecret.sh        
    - chmod 0755 ./run.sh
    - ./run.sh    
    - exit_code=$?
    - if [ $exit_code -eq 0 ]; then echo "Build succeeded !"; else echo "Build failed"; fi
  tags:
    - "t-008-deploy"
