image: docker:latest

services:
  - docker:dind

stages:
  - build_push

before_script:
  - echo "$T015_DOCKER_HUB_TOKEN" | docker login -u "$T015_REGISTRY_USER_NAME" --password-stdin

.build_push_template:
  stage: build_push
  script:
    - chmod 0755 ./ci-scripts/build_push_images.sh
    - ./ci-scripts/build_push_images.sh
  tags:
    - t-015-build-protected

qr_build_push:
  extends: .build_push_template
  variables:
    image_name: qr
    image_tag: dev

backend_build_push:
  extends: .build_push_template
  variables:
    image_name: backend
    image_tag: dev

website_build_push:
  extends: .build_push_template
  variables:
    image_name: website
    image_tag: dev
