#!/bin/bash
IMAGE_NAME=$1
REGISTRY_USERNAME=$2
REGISTRY_PASSWORD=$3

docker login -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD"
docker tag "$IMAGE_NAME:dev" "$REGISTRY_USERNAME/$IMAGE_NAME:dev"
docker push "$REGISTRY_USERNAME/$IMAGE_NAME:dev"