apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
- namespaces.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

configMapGenerator:
- name: frontconfig
  namespace: training-app-frontend-prod
  behavior: create
  files:
  - configmap-files/app-config.json