apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-qr-config
  namespace: {{ .Values.backendNamespace }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  BUCKET_NAME: {{ .Values.qrConfig.bucketName | quote }}
  BUCKET_PATH: {{ .Values.qrConfig.bucketPath | quote }}
  QR_BACKGROUND_COLOR: {{ .Values.qrConfig.qrBackgroundColor | quote }}
  QR_FILL_COLOR: {{ .Values.qrConfig.qrFillColor | quote }}
  QR_TMP_FOLDER: {{ .Values.qrConfig.qrTmpFolder | quote }}
  USE_BUCKET: {{ .Values.qrConfig.useBucket | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-qr-deployment
  namespace: {{ .Values.backendNamespace }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.qrDeployment.replicas }}
  selector:
    matchLabels:
      app: qr
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: qr
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: {{ include "chart.fullname" . }}-qr-config
        - secretRef:
            name: {{ include "chart.fullname" . }}-s3-secret
        image: {{ .Values.qrDeployment.qr.image.repository }}:{{ .Values.qrDeployment.qr.image.tag }}
        name: qr
        ports:
        - containerPort: 8420
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-qr-service
  namespace: {{ .Values.backendNamespace }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.qrService.type }}
  selector:
    app: qr
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.qrService.ports | toYaml | nindent 2 }}