apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-s3-secret
  namespace: {{ .Values.backendNamespace }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  BUCKET_ACCESS_KEY: {{ required "s3Secret.bucketAccessKey is required" .Values.s3Secret.bucketAccessKey
    | b64enc | quote }}
  BUCKET_ENDPOINT: {{ required "s3Secret.bucketEndpoint is required" .Values.s3Secret.bucketEndpoint
    | b64enc | quote }}
  BUCKET_SECRET_KEY: {{ required "s3Secret.bucketSecretKey is required" .Values.s3Secret.bucketSecretKey
    | b64enc | quote }}
type: Opaque