apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-website-configmap
  namespace: {{ .Values.frontendNamespace }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  app-config.json: |-
    {
      "backendUrl": "https://backend.com/access"
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: {{ .Values.frontendNamespace }}
spec:
  replicas: {{ .Values.website.replicas }}
  selector:
    matchLabels:
      app: website
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: website
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.website.website.image.repository }}:{{ .Values.website.website.image.tag
          | default .Chart.AppVersion }}
        name: website
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/nginx/html/assets/configs
          name: configs
      volumes:
      - configMap:
          name: {{ include "chart.fullname" . }}-website-configmap
        name: configs
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-website-service
  namespace: {{ .Values.frontendNamespace }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.websiteService.type }}
  selector:
    app: website
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.websiteService.ports | toYaml | nindent 2 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}-website-ingress
  namespace: {{ .Values.frontendNamespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure

  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  rules:
  - host: app.frontend.local
    http:
      paths:
      - backend:
          service:
            name: '{{ include "chart.fullname" . }}-website-service'
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - app.frontend.local
  - secretName: tls-secret