{{- range $app := .Values.apps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $app.app }}
  name: {{ $app.app }}
  namespace: {{ $app.namespace }}
spec:
  replicas: {{ $app.replicas }}
  selector:
    matchLabels:
      app: {{ $app.app }}
  template:
    metadata:
      labels:
        app: {{ $app.app }}
    spec:
      containers:
      {{- range $val := $app.containers }}
        - image: {{ $val.image }}
          name: {{ $val.name }}
          resources:
            limits:
              memory: {{ $val.resources.limits.memory }}
              cpu: {{ $val.resources.limits.cpu }}
          ports:
            - containerPort: {{ $val.port }}
          {{- if $val.env }}
          env:
            {{- range $env :=  $val.env }}
            - name: {{ $env.name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $env.secretName }}
                  key: {{ $env.secretKey }}
            {{- end }}
          {{- end }}
        {{- if $val.volumeMounts }}
          {{- range $vol := $val.volumeMounts }}
          volumeMounts:
            - name: {{ $vol.name }}
              mountPath: {{ $vol.mountPath }}
            {{- end }}
        {{- end }}
      {{- end }}
      {{- if $app.volumes }}
      volumes:
        {{- range $vol := $app.volumes }}
        - name: {{ $vol.name }}
          {{- if $vol.configmap}}
          configMap:
            name: {{ $vol.configmap.name }}
          {{- end }}
        {{- end }}
      {{- end }}
{{- end }}


        