{{- range $app := .Values.apps }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $app.service.name }}
  namespace: {{ $app.namespace }}
spec:
  type: {{ $app.service.type }}
  ports:
    - port: {{ $app.service.port }}
      targetPort: {{ $app.service.targetPort }}
  selector:
    app: {{ $app.app }}
{{- end}}
