apiVersion: v1
kind: ConfigMap
metadata:
  name: qr-config  
data:
  QR_TMP_FOLDER: "./generated_qr"
  QR_FILL_COLOR: "#121128"
  QR_BACKGROUND_COLOR: "#dcdbdb"
  APP_PORT: "8420"
  USE_BUCKET: "true"
  BUCKET_ENDPOINT: "play.min.io"
  BUCKET_ACCESS_KEY: "881VXUUQF99AYMDWR4XC"
  BUCKET_SECRET_KEY: "PdfE1EEpQk9BRgPJvLwH1rfwpYxKnsczDfiLTZe7"
  secure: "True"
  BUCKET_NAME: "mytest"
  BUCKET_PATH: "training_data"
  BUCKET_REGION: "us-east-1"
     