#! /bin/bash

## NOTE ##

## For now , this file isn't used . TLS certificatE and private key have been generated by running : 
## openssl req -x509 -newkey rsa:2048 -nodes -keyout localhost.key -out localhost.crt -days 365 -subj "/CN=localhost" 

## END NOTE ##



sudo apt-get update
#using OpenSSL instead of Let's Encrypt 
sudo apt-get install certbot

openssl req -x509 -newkey rsa:2048 -nodes -keyout localhost.key -out localhost.crt -days 365 -subj "/CN=localhost"

DOMAIN="localhost"

# Stop Nginx to avoid port conflicts
sudo systemctl stop nginx

# Update Nginx configuration to use the self-signed certificate and key
# SSL_CERTIFICATE_PATH="/nginx"
# SSL_CERTIFICATE_KEY_PATH="/path/to/localhost.key"

source .env

sudo sed -i "s|ssl_certificate .*|ssl_certificate $SSL_CERTIFICATE_PATH;|" /etc/nginx/sites-available/$DOMAIN
sudo sed -i "s|ssl_certificate_key .*|ssl_certificate_key $SSL_CERTIFICATE_KEY_PATH;|" /etc/nginx/sites-available/$DOMAIN

# Start Nginx after updating the configuration
# sudo systemctl start nginx