version: '3'
services:

  qr:
    extends:
      file: docker-compose-B.yml
      service: qr
    networks:
      - private_network
    depends_on:
      - minios3
    deploy:
      mode: replicated
      replicas: 2


  website:
    extends:
      file: docker-compose-B.yml
      service: website
    networks:
      - public_network
    deploy:
      mode: replicated
      replicas: 2    


  backend:    
    extends:
      file: docker-compose-B.yml
      service: backend
    networks:
      - private_network
    depends_on:
      - qr
    deploy:
      mode: replicated
      replicas: 2


  minios3:    
    extends:
      file: docker-compose-B.yml
      service: minios3
    networks:
      - private_network


  nginxproxy:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl/localhost.crt:/etc/localhost.crt
      - ./ssl/localhost.decrypted.key:/etc/localhost.decrypted.key
      - ./ssl/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - private_network
      - public_network
    depends_on:
      - qr
      - backend
      - website


networks:
  private_network:
  public_network:

volumes:
  app-volume:
  qrVolume:
