version: "3.8"
services:
  qr:
    image: tayssirgh/t013-website
    container_name: qr
    build:
      context: ./qr
    environment:
      - QR_TMP_FOLDER="./generated_qr"
      - QR_FILL_COLOR="#121128"
      - QR_BACKGROUND_COLOR="#dcdbdb"
      - USE_BUCKET=true
    ports:
      - "8420:8420"
    networks:
      - qr_net
    volumes:
      - qr-code:/qr/generated_qr
  backend:
    image: tayssirgh/t013-backend
    container_name: backend
    environment:
      - APP_PORT=3000
      - QR_URL=http://localhost:8420/
      - MONGO_URI=mongodb+srv://tayssir:9F98N3PS@cluster0.xziulww.mongodb.net
    build:
      context: ./backend
    ports:
      - "8082:3000"
  website:
    image: tayssirgh/t013-website
    container_name: website
    build:
      context: ./website
    ports:
      - "80:80"
    volumes:
      - qr-code:/applications/website/src/assets/data
networks:
  qr_net :
    driver: bridge
volumes:
  qr-code: