services:
  backend:
    env_file:
      - backend.env
  minio:
    env_file:
      - minio.env
  nginx:
    image: nginx:1.19.2-alpine
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - minio
    networks:
      - public-net
networks:
  public-net: