version: '3'
services:

  qr:
    image: qr
    build:
      context: ./qr
    env_file:
      - qr/.env
    volumes:
      - qrVolume:/app/scripts/generated_qr

  backend:
    image: backend
    build:
      context: ./backend
    env_file:
      - backend/.env

  website:
    image: website
    build:
      context: ./website
    volumes:
      - qrVolume:/app/scripts/generated_qr

volumes:
  qrVolume:
