version : '3'

services  :

  backend:
    build:
        context: ./backend
    image: orcasifilus/t-003-backend
    ports:
      - "8082:3000"
    env_file:
      - ./backend/.env

  qr :
    build:
        context: ./qr
    image : orcasifilus/t-003-qr
    ports:
      - "4000:4000"
    env_file:
      - ./qr/.env
    volumes:
    - app:/qr/scripts/qr_generator.py
    networks:
    - app-netw

  website:
    build:
        context: ./website/src
    image : orcasifilus/t-003-website
    ports :
      - "80:80"
    volumes :
    - app:/website/src/assets/data
    networks:
    - app-netw

volumes:
  app:
networks:
  app-netw: