
services:
  qr:
    extends:
      file: docker-compose-A.yml
      service: qr

  backend:
    extends:
      file: docker-compose-A.yml
      service: backend


  website:
    extends:
      file: docker-compose-A.yml
      service: website
  minio:
    image: minio/minio:latest
    container_name: minio

    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - qr_net
    volumes:
      - 'minio-data:/data'
    command: server /data --console-address ":9001"
volumes:
  qr-code:
  minio-data:
networks:
  qr_net:
    driver: bridge


