version: "3.8"
services:
  qr:
    image: tayssirgh/t013-website
    container_name: qr
    build:
      context: ./qr
    ports:
      - "8420:8420"
    networks:
      - qr_net
    volumes:
      - qr-code:./qr/generated_qr
  backend:
    image: tayssirgh/t013-backend
    container_name: backend
    build:
      context: ./backend
    ports:
      - "8082:3000"
  website:
    image: tayssirgh/t013-website
    container_name: website
    build:
      context: ./website
    ports:
      - "80:80"
    volumes:
      - qr-code:./applications/website/src/assets/data
networks:
  qr_net :
    driver: bridge
volumes:
  qr-code: