
services:
  qr:
    extends:
      file: docker-compose-A.yml
      service: qr

  backend:
    extends:
      file: docker-compose-A.yml
      service: backend


  website:
    extends:
      file: docker-compose-A.yml
      service: website
volumes:
  qr-code:
    driver: local

networks:
  qr_net:
    driver: bridge


