version: '3'

services:

  qr:
    build: 
      context: ./qr
      dockerfile: Dockerfile
    env_file:
      - ./qr/.env
    volumes:
      - qr_volume:/generated_qr
    networks:
      - privatenetwork

    
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    depends_on:
      - qr
    networks:
      - privatenetwork


  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
      - qr
    volumes:
      - qr_volume:/generated_qr  
    networks:
      - appnetwork

networks:
  appnetwork:
  privatenetwork:

volumes:
  qr_volume:
