version: "3.8"

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  node_api:
    image: node-api:latest
    container_name: node_api
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
      target: node_api 
    ports:
      - 3000:3000
    networks:
      - api
    depends_on: 
      - mongo_db
    env_file:
      - .env

  qr_api:
    image: qr-api:latest
    container_name: qr_api
    restart: always
    build:
      context: qr
      dockerfile: Dockerfile
      target: qr_api
    networks:
      - api
    ports:
      - 8420:8420
    env_file:
      - .env

  app_ui:
    image: app-ui:latest
    container_name: app_ui
    restart: always
    build:
      context: website
      dockerfile: Dockerfile
      target: app_ui
    networks:
      - api
    depends_on:
      - mongo_db
    ports:
      - 8666:80
    env_file:
      - .env

networks:
  api:
    driver: bridge

volumes:
  mongo_data: {}
