version: '3'
services:

  qr:
    image: xqliza/t005-qr
    env_file:
      - qr/.env
    volumes:
      - qrVolume:/app/scripts/generated_qr

  backend:
    image: xqliza/t005-backend
    build:
      context: ./backend
    env_file:
      - backend/.env

  website:
    image: xqliza/t005-website
    volumes:
      - qrVolume:/app/scripts/generated_qr

volumes:
  qrVolume:
