version: '3.0'
services:
    web_backend:
      image: mghodben/t001-backend
      ports:
          - "8082:8085"
    web_website:
      image: mghodben/t001-website
      ports:
        - "80:8086"
      volumes:
        - shared-volume:$SHARED_VOLUME_WEBSITE
    qr:
      image: mghodben/t001-qr
      ports:
        - "8085:8087"
      volumes:
        - shared-volume:$SHARED_VOLUME_QR
      networks:
        - qr-network
volumes:
  shared-volume:
networks:
   qr-network: