version: "3.8"

services:
  qr:
    extends:
      file: docker-compose-A.yml
      service: qr

  backend:
    extends:
      file: docker-compose-A.yml
      service: backend


  website:
    extends:
      file: docker-compose-A.yml
      service: website

