version : '3'

services  :

  backend :
    build :
        context: ./applications/backend/services
    image : orcasifilus/t-003-backend
    ports:
      - "8082:8082"
    env_file:
      -.env

  website :
    build :
        context : ./applications/website/src
    image : orcasifilus/t-003-website
    ports :
      - "80:80"
  volumes :
    - app:applications/qr/scripts
  networks:
    - app-netw

  qr :
    build :
        context : ./applications/qr
    image : orcasifilus/t-003-qr
    env_file:
      -.env
  volumes :
  - app:applications/qr/scripts
  networks:
    - app-netw

volumes:
  app:
networks:
  app-netw: