version: "3.8"

services:
  qr:
    image: khalilmk/t010:qr-1.0
    container_name: qr
    restart: always
    build:
      context: ./qr
    
    ports:
      - 8000:8000
    env_file:
      - ./qr/.env
    volumes:
      - minio-data:/app/generated_qr/
    networks:
      - qr_network

  backend:
    image: khalilmk/t010:backend-1.0
    container_name: backend
    restart: always
    environment:
      - APP_PORT=3000
      - QR_URL=http://qr:8000
      - MONGO_URI=mongodb+srv://houssein:kairouan@cluster0.0tc12ie.mongodb.net
    build:
      context: ./backend
    networks:
      - app_network
      - qr_network
    ports:
      - 8082:3000
    env_file:
      - ./backend/.env
  website:
    image: khalilmk/t010:website-1.0
    container_name: website
    restart: always
    build:
      context: ./website
    networks:
      - app_network
    ports:
      - 80:80
    volumes:
      - minio-data:/usr/share/nginx/html/assets/data

  
networks:
  qr_network:
    driver: bridge
  app_network:
    driver: bridge
volumes:
  minio-data:

