version: "3.9"
services:

  load_balancer:
    image: nginx:latest
    container_name: load_balancer
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - generated_qr:/etc/nginx/html/assets/data
      - web_data:/etc/nginx/html
    networks:
      - qr_network
      - app_network
    depends_on:
      - website
      - backend
      - minio
      - qr

  qr:
    image: housseinhmila/t-007-qr
    
    build:
      context: ./qr
    restart: always
    deploy:
     
      replicas: 2
    ports: 
      - 8420
    environment:
      - QR_TMP_FOLDER="./generated_qr"
      - QR_FILL_COLOR="#121128"
      - QR_BACKGROUND_COLOR="#dcdbdb"
      - USE_BUCKET=true
      - BUCKET_ENDPOINT="myminio:9000"
      - BUCKET_ACCESS_KEY="7A0bbzvFVmsJkx2Irqcw"
      - BUCKET_SECRET_KEY="FDLGkVgOpek5g91OQVTPRgjjiyAK4gYKButkZ7kf"
      - BUCKET_NAME="test"
      - BUCKET_PATH=""
    depends_on:
      - minio
    volumes:
      - generated_qr:/app/generated_qr/
    networks:
      - qr_network

  backend:
    image: housseinhmila/t-007-backend
    
    build:
      context: ./backend
    restart: always
    ports: 
     - 3000
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - qr
    environment:
      - APP_PORT=3000
      - QR_URL=http://qr:8420
      - MONGO_URI=mongodb+srv://houssein:kairouan@cluster0.0tc12ie.mongodb.net
      - MONGO_DB=test

    networks:
      - qr_network
      - app_network

  website:
    image: housseinhmila/t-007-website
    build:
      context: ./website
    restart: always
    deploy:
      mode: replicated
      replicas: 2
    ports: 
     - 4200
    depends_on:
      - backend
    volumes:
    - web_data:/usr/share/nginx/html 
    networks:
      - app_network

  minio:
    image: minio/minio
    container_name: myminio
    environment:
      - MINIO_ROOT_USER=strass
      - MINIO_ROOT_PASSWORD=strass22
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio_data:/data
    networks:
      - qr_network
      - app_network
   

volumes:
  generated_qr:
  minio_data:
  web_data:

networks:
  app_network:
  qr_network:
