version: '3.0'
services:
    web_backend:
      image: mghodben/t001-backend
      build: backend/
      ports:
          - "8082:3000"
      env_file:
        - backend.env
      environment:
        - NODE_ENV=production
      networks:
        - qr-network
    web_website:
      image: mghodben/t001-website
      build: website/
      ports:
        - "8090:80"
      volumes:
        - shared-volume:/usr/share/nginx/html
      networks:
        - qr-network
    qr:
      image: mghodben/t001-qr
      build: qr/
      ports:
        - "8085:8420"
      env_file:
        - qr.env
      volumes:
        - shared-volume:/usr/share/nginx/html
      networks:
        - qr-network
volumes:
  shared-volume:
networks:
   qr-network: