version: '3'
services:

  qr:
    image: xqliza/t005-qr
    environment:
      - QR_TMP_FOLDER="./generated_qr"
      - QR_FILL_COLOR="#121128"
      - QR_BACKGROUND_COLOR="#dcdbdb"
      - USE_BUCKET=true
      - BUCKET_ENDPOINT=$T005_BUCKET_ENDPOINT
      - BUCKET_ACCESS_KEY=$T005_BUCKET_ACCESS_KEY
      - BUCKET_SECRET_KEY=$T005_BUCKET_SECRET_KEY
      - BUCKET_NAME="testbucketio"
      - BUCKET_PATH="/data"
    volumes:
      - qrVolume:/app/scripts/generated_qr

  backend:
    image: xqliza/t005-backend
    build:
      context: ./backend
    environment:
      - APP_PORT=3000
      - QR_URL=http://qr:8420/
      - MONGO_URI=$T005_MONGO_URI
      - MONGO_DB=qrs

  website:
    image: xqliza/t005-website
    volumes:
      - qrVolume:/app/scripts/generated_qr

volumes:
  qrVolume:
