version: '3.0'
services:
    backend:
      image: mghodben/t001-backend
      ports:
          - 8082:3000
      env_file:
        - backend/.env
      depends_on:
        - qr
      environment:
        - NODE_ENV=production
      networks:
        - qr-network
        - public-net
    website:
      image: mghodben/t001-website
      ports:
        - 4200:80
      volumes:
        - shared-volume:/usr/share/nginx/html/assets/data
        - ./app-config.json:/usr/share/nginx/html/assets/configs/app-config.json
      networks:
        - public-net
      depends_on:
        - backend
    qr:
      image: mghodben/t001-qr
      ports:
        - 8420:8420
      env_file:
        - qr/.env
      networks:
        - qr-network
      volumes:
        - shared-volume:/app/generated_qr
volumes:
  shared-volume:
networks:
  qr-network:
    external: false
  public-net: