version: "3.8"
services:
  qr:
    build: ./qr
    ports:
      - "8420:8420"
  backend:
    build: ./backend
    ports:
      - "8082:3000"
  website:
    build: ./website
    ports:
      - "80:80"
    networks:
      - private_network
networks:
  private_network :
    driver: bridge