version: "3.8"
services:
    backend:
        image: abdelkaderbrahem/t002-backend:dev
        container_name: backend 
        env_file: 
          - backend.env
        ports: 
          - 8082:8082
        environment:
          - NODE_ENV=production
        networks: 
          - private-network
        build: 
            context: backend          
 
    website :
        image : abdelkaderbrahem/t002-website:dev
        container_name: website
        depends_on: 
          - backend
        volumes: 
          - app-volume:/usr/share/nginx/html/assets/data:z
          - ./app-config.json:/usr/share/nginx/html/assets/configs/app-config.json
        environment:
          - NODE_ENV=production
        networks: 
          - private-network
        build: 
            context: website
 
    qr:
        image: abdelkaderbrahem/t002-qr:dev
        container_name: qr 
        networks: 
          - private-network
        env_file: 
          - qr.env
        volumes: 
          - app-volume:/app/generated_qr:z
        build: 
            context: qr

    nginx:
        image: nginx:1.19.2-alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - app-volume:/usr/share/nginx/html/assets/data:z
            - ./app-config.json:/usr/share/nginx/html/assets/configs/app-config.json
        ports:
          - 80:80
        networks: 
          - public-network  
          - private-network
        depends_on: 
          - backend
          - website
          - qr

networks:
    public-network:   
    private-network:
      external: false      
volumes:
    app-volume: 
                