version: "3.8"
services:
    backend:
        image: abdelkaderbrahem/t002-backend:dev
        container_name: backend 
        ports:
            - 8082:8082
        env_file: 
            - backend.env
        environment:
            - NODE_ENV=production
        networks: 
            - private-network
            - public-network
          
    website :
        image : abdelkaderbrahem/t002-website:dev
        container_name: website
        ports:
            - 80:80
        depends_on: 
            - backend
        volumes: 
            - app-volume:/usr/share/nginx/html/assets/data:z
            - ./app-config.json:/usr/share/nginx/html/assets/configs/app-config.json
        environment:
            - NODE_ENV=production
        networks: 
            - public-network

    qr:
        image: abdelkaderbrahem/t002-qr:dev
        container_name: qr 
        ports:
            - 8420:8420
        networks: 
            - private-network
        env_file: 
            - qr.env
        volumes: 
            - app-volume:/app/generated_qr:z

networks:
    public-network:   
    private-network:   
volumes:
    app-volume: 
                  