services:
  minio:
    extends:
      file: docker-compose-C.yaml
      service: minio
  qr:
    extends:
      file: docker-compose-C.yaml
      service: qr
  backend:
    extends:
      file: docker-compose-C.yaml
      service: backend
  website:
    extends:
      file: docker-compose-C.yaml
      service: website
  nginx:
    image: nginx:latest
    volumes:
      - applications/proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/private/nginx-selfsigned.key:/etc/nginx/ssl/private.key
      - /etc/ssl/certs/nginx-selfsigned.crt:/etc/nginx/ssl/certificate.crt
      - qr-code:/etc/nginx/html/assets/data
    ports:
      - 80:80
      - 443:443
    networks:
      - qr_net
    depends_on:
      - website
networks:
  qr_net:
    driver: bridge
volumes:
  qr-code:
  minio-data:
