version: '3'
services:

  qr:
    container_name: qr
    extends:
      file: docker-compose-B.yml
      service: qr
    networks:
      - private_network
    depends_on:
      - minios3

  website:
    container_name: websiteA
    extends:
      file: docker-compose-B.yml
      service: website
    networks:
      - private_network

  backend:
    container_name: backend
    extends:
      file: docker-compose-B.yml
      service: backend
    ports:
      - 8082:3000
    networks:
      - private_network
    depends_on:
      - qr

  minios3:
    container_name: minios3
    extends:
      file: docker-compose-B.yml
      service: minios3
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - private_network
    command: server /data --console-address ":9001"

  nginxproxy:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - public_network
      - private_network
    depends_on:
      - qr
      - backend
      - website

networks:
  private_network:
    external: false
  public_network:


volumes:
  app-volume:
  qrVolume:
