version: "3.8"

services:
  qr:
    image: khalilmk/t010:qr-1.0
    restart: always
    build:
      context: ./qr
      dockerfile: Dockerfile 
    networks:
      - qr_network
    ports:
      - 8000
    deploy:
      mode: replicated
      replicas: 2

    volumes:
      - minio-data:/app/generated_qr/
    networks:
      - qr_network


  backend:
    image: khalilmk/t010:backend-1.0
    restart: always
    environment:
      - backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile 
    deploy:
      replicas: 2
    depends_on: 
      - qr
    networks:
      - app_network
      - qr_network
    ports:
      - 3000


  website:
    image: khalilmk/t010:website-1.0
    restart: always
    build:
      context: ./website
      dockerfile: Dockerfile 
    depends_on: 
      - backend
    deploy:
      replicas: 2
    networks:
      - app_network
    ports:
      - 80
    volumes:
      - minio-data:/usr/share/nginx/html/assets/data


  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=test_user
      - MINIO_ROOT_PASSWORD=test_password
    command: server /data --console-address ":9001"
    networks:
      - app_network

  # load_balancer_ssl:
  #   image: nginx:latest
  #   container_name: load_balancer_ssl
  #   ports:
  #     - 80:80
  #     - 443:443
  #   networks:
  #     - qr_network
  #     - app_network
  #   depends_on:
  #     - website
  #     - backend
  #     - minio
  #     - qr
  #   volumes:
  #     - ./nginx/nginx1.conf:/etc/nginx/conf.d/default.conf
  #     - minio-data:/etc/nginx/html/assets/data
  #     - ./nginx/my-site.crt:/etc/ssl/certs/my-site.crt
  #     - ./nginx/my-site.key:/etc/ssl/private/my-site.key

    load_balancer:
      image: load_balancer
      container_name: load_balancer
      build:
        context: ./nginx
        dockerfile: Dockerfile 
      ports:
        - 80:80

      networks:
        - qr_network
        - app_network
      depends_on:
        - website
        - backend
        - minio
        - qr

  
networks:
  qr_network:
  app_network:
    driver: bridge
volumes:
  minio-data:

