services:
  minio:
    extends:
      file: docker-compose-B.yaml
      service: minio

  qr:
    image: tayssirgh/t013-qr
    environment:
      - QR_TMP_FOLDER="./generated_qr"
      - QR_FILL_COLOR="#121128"
      - QR_BACKGROUND_COLOR="#dcdbdb"
      - USE_BUCKET=true
      - BUCKET_ENDPOINT="play.min.io:9000"
      - BUCKET_ACCESS_KEY="Q3AM3UQ867SPQQA43P2F"
      - BUCKET_SECRET_KEY="zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
      - BUCKET_NAME="test"
      - BUCKET_PATH=""
    networks:
      - qr_net
    volumes:
        - qr-code:/qr/generated_qr
    deploy:
      replicas: 2
    depends_on:
      - minio

  backend:
    image: tayssirgh/t013-backend
    environment:
      - APP_PORT=3000
      - QR_URL=http://qr:8420/
      - MONGO_URI=mongodb+srv://tayssir:9F98N3PS@cluster0.xziulww.mongodb.net
    networks:
      - qr_net
    depends_on:
      - qr
    deploy:
      replicas: 2

  website:
    image: tayssirgh/t013-website
    depends_on:
      - backend
    networks:
      - qr_net
    volumes:
      - ./website/src/assets/configs:/usr/share/nginx/html/assets/configs
      - qr-code:/src/assets/data
    deploy:
      replicas: 2

  nginx:
    image: nginx:latest
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - qr-code:/etc/nginx/html/assets/data
    ports:
      - 80:80
    networks:
      - qr_net
    depends_on:
      - website


networks:
  qr_net:
    driver: bridge
volumes:
  qr-code:
  minio-data: