services:
  qr:
    image: tayssirgh/t013-qr:dev
    container_name: qr
    env_file: ./qr/.env
    ports:
      - "8420:8420"
    networks:
      - qr_net
  backend:
    image: tayssirgh/t013-backend
    container_name: backend
    environment:
      - APP_PORT=3000
      - QR_URL=http://qr:8420/
      - MONGO_URI=mongodb+srv://tayssir:9F98N3PS@cluster0.xziulww.mongodb.net
    depends_on:
      - qr
    ports:
      - "3000:3000"
    networks:
      - qr_net
  website:
    image: tayssirgh/t013-website
    container_name: website
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - qr_net
    volumes:
      - ./website/src/assets/configs:/usr/share/nginx/html/assets/configs
networks:
  qr_net :
    driver: bridge
