version: '3'

services:

  qr:
    build: 
      context: ./qr
      dockerfile: Dockerfile
    environment:
      - QR_TMP_FOLDER=./generated_qr
      - QR_FILL_COLOR=121128
      - QR_BACKGROUND_COLOR=dcdbdb
      - USE_BUCKET=true
      - BUCKET_ENDPOINT=minios3:9000
      - BUCKET_ACCESS_KEY=t99UOOdftLikKTikuNmF
      - BUCKET_SECRET_KEY=lroJCZOzj2L38n0aTyA6osWUzzwFX6PgFVvfR1BZ
      - BUCKET_NAME=qrbacket
      - BUCKET_PATH=qrbacket
    volumes:
      - qr_volume:/generated_qr
    networks:
      - privatenetwork

    
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - APP_PORT=3040
      - QR_URL=http://qr:8420
      - MONGO_URI=mongodb+srv://azizos:azizos123@azizos.u0tduhr.mongodb.net
      - MONGO_DB=azizos
    depends_on:
      - qr
    networks:
      - privatenetwork


  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
      - qr
    volumes:
      - qr_volume:/generated_qr  
    networks:
      - appnetwork

networks:
  appnetwork:
  privatenetwork:

volumes:
  qr_volume:
