# values.yaml

deployment:
  website: 
    image: "ilefrjiba/t-014-website"
    port: 80

  qr: 
    image: "ilefrjiba/t-014-qr"
    port: 8420

  backend:
    image: "ilefrjiba/t-014-backend"
    port: 3000

secret:
  s3:
    BUCKET_ACCESS_KEY: UTNBTTNVUTg2N1NQUVFBNDNQMkY=
    BUCKET_SECRET_KEY: enVmK3RmdGVTbHN3UnU3Qko4Nndla2l0bmlmSUxiWmFtMUtZWTNURw==
    BUCKET_ENDPOINT: cGxheS5taW4uaW86OTAwMA==

  backend:
    APP_PORT: MzAwMAo=

