---
- hosts: webservers
  become: true

  tasks:
    - name: Install Docker
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Add current user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create application directory
      file:
        path: /home/{{ ansible_user }}/app
        state: directory

    - name: Copy Docker Compose file to VM
      copy:
        src: ../../docker-compose-A.yml
        dest: /home/{{ ansible_user }}/app/docker-compose.yml

    - name: Copy .env files to VM
      copy:
        src: ../../qr/.env
        dest: /home/{{ ansible_user }}/app/qr/.env


    - name: Start the application with Docker Compose
      shell: docker-compose up -d
      args:
        chdir: /home/{{ ansible_user }}/app
