namespaces:
  - name: training-app-frontend-prod
  - name: training-app-backend-prod

apps:
  - app: backend 
    namespace: training-app-backend-prod
    name: backend
    replicas: 1
    containers:
      - image: youssef2023/comwork-backend:v2-latest
        name: backend-container
        imagePullPolicy: Always
        env:
          - name: APP_PORT
            secretName: backend-secret
            secretKey: APP_PORT
          - name: QR_URL
            secretName: backend-secret
            secretKey: QR_URL
          - name: MONGO_URI
            secretName: backend-secret
            secretKey: MONGO_URI
          - name: MONGO_DB
            secretName: backend-secret
            secretKey: MONGO_DB
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
          containerPort: 3000
          name: backend    
      - image: youssef2023/comwork-qr:v2-latest
        name: qr-container
        imagePullPolicy: Always
        env:
          - name: QR_TMP_FOLDER
            secretName: qr-secret
            secretKey: QR_TMP_FOLDER
          - name: QR_FILL_COLOR
            secretName: qr-secret
            secretKey: QR_FILL_COLOR
          - name: QR_BACKGROUND_COLOR
            secretName: qr-secret
            secretKey: QR_BACKGROUND_COLOR
          - name: USE_BUCKET
            secretName: qr-secret
            secretKey: USE_BUCKET
          - name: BUCKET_ENDPOINT
            secretName: qr-secret
            secretKey: BUCKET_ENDPOINT
          - name: BUCKET_ENDPOINT_WEB
            secretName: qr-secret
            secretKey: BUCKET_ENDPOINT_WEB           
          - name: BUCKET_NAME
            secretName: qr-secret
            secretKey: BUCKET_NAME
          - name: BUCKET_ACCESS_KEY
            secretName: qr-secret
            secretKey: BUCKET_ACCESS_KEY
          - name: BUCKET_SECRET_KEY
            secretName: qr-secret
            secretKey: BUCKET_SECRET_KEY
        resources:
          limits:
            memory: "200Mi"
            cpu: "100m"
        ports:
          containerPort: 8420
          name: qr            

    service:
      type: LoadBalancer
      port: 80
      targetPort: 3000
      name: backend-service

    ingress:
      name: ingress-backend
      annotations:
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /$2
      host: localhost
      path: /api(/|$)(.*)
      pathType: Prefix
      ingressClassName: nginx

  - app: frontend 
    namespace: training-app-frontend-prod
    replicas: 1
    name: frontend    
    containers:
      - image:  youssef2023/comwork-website:v2
        name: application-website
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
          containerPort: 4200
        volumeMounts:
          - name: configs
            mountPath: /etc/nginx/html/assets/configs
    volumes:
      name: configs
      configMap:
        name: configs-front

    service:
      type: LoadBalancer
      port: 80
      targetPort: 4200
      name: frontend-service

    ingress:
      name: ingress-frontend
      host: localhost
      path: /
      pathType: Prefix
      ingressClassName: nginx

    configmap:
      - name: configs-front
        namespace: training-app-frontend-prod
        files: 
        - filename: "app-config.json"
          path: "configs"

secrets:
  - name: qr-secret
    namespace: training-app-backend-prod
    data:
      QR_TMP_FOLDER: ./generated_qr
      QR_FILL_COLOR: "#121128"
      QR_BACKGROUND_COLOR: "#dcdbdb"
      USE_BUCKET: "true"
      BUCKET_ENDPOINT: play.min.io:9000
      BUCKET_ENDPOINT_WEB: play.min.io:9000
      BUCKET_ACCESS_KEY: cOhulffMgL0wrY67zIZ8 
      BUCKET_SECRET_KEY: q5esGiHuiBgun7r1HBUYv4PXLGszDYLK8KxlB3KA
      BUCKET_NAME: "teeest"
      BUCKET_PATH: ""
  - name: backend-secret
    namespace: training-app-backend-prod
    data:
      APP_PORT: "3000"
      QR_URL: http://localhost:8420/
      MONGO_URI: mongodb+srv://youssef:2pWCU0mFB84q1HRI@cluster0.nqpem.mongodb.net
      MONGO_DB: comwork
