apiVersion: apps/v1
kind: Deployment
metadata: 
  name:  backend-deployment
  labels: 
    app: backend
spec: 
  template: 
      metadata: 
        name: backend-pod
        labels: 
          app: backend 
      spec: 
        containers: 
          - image: abdelkaderbrahem/t002-backend:dev
            name: backend
            ports:
            - containerPort: 3000
            envFrom:
            - configMapRef:
                name: backend-config
            env:
              - name: MONGO_URI
                valueFrom:
                  secretKeyRef:
                    name: backend-secret
                    key: MONGO_URI
                    
  selector:
      matchLabels:
        app: backend