apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: training-app-backend-prod
data:
  APP_PORT : "3000"
  QR_URL : "http://qr-service:8420/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: training-app-backend-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: tayssirgh/t013-backend:dev
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: db-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: training-app-backend-prod
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: training-app-backend-prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - "app.backend.local"
    - secretName: tls-backend-secret
  rules:
    - host: "app.backend.local"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: backend-service
                port:
                  number: 3000
  ingressClassName: nginx
