apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: training-app-backend-prod
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly90YXlzc2lyOjlGOThOM1BTQGNsdXN0ZXIwLnh6aXVsd3cubW9uZ29kYi5uZXQ=
