apiVersion: v1
kind: ConfigMap
metadata:
  name: website-configmap
  namespace: training-app-frontend-prod
data:
  app-config.json: |-
    {
      "backendUrl": "https://app.backend.local/access"
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: training-app-frontend-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: tayssirgh/t013-website:dev
          ports:
            - containerPort: 80
          volumeMounts:
            - name: configs
              mountPath: /usr/share/nginx/html/assets/configs
      volumes:
        - name: configs
          configMap:
            name: website-configmap


---
apiVersion: v1
kind: Service
metadata:
  name: website-service
  namespace: training-app-frontend-prod
spec:
  selector:
    app: website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website-ingress
  namespace: training-app-frontend-prod
spec:
  tls:
    - hosts:
        - "app.frontend.local"
    - secretName: tls-secret
  rules:
    - host: "app.frontend.local"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: website-service
                port:
                  number: 80
  ingressClassName: nginx
