apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: training-app-frontend-prod
spec:
  resources:
    requests:
      storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      type: local