apiVersion: v1
kind: Secret
metadata:
  name: qr-secret
  namespace: training-app-backend-prod
type: Opaque
stringData:
  USE_BUCKET: "true"
  BUCKET_ENDPOINT: "play.min.io:9000"
  BUCKET_ACCESS_KEY: Q3AM3UQ867SPQQA43P2F
  BUCKET_SECRET_KEY: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
  BUCKET_NAME: testbucketio
  BUCKET_PATH: /data