apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  namespace: training-app-frontend-prod
  labels:
    type: local
spec:
  capacity:
    storage: 2Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /home/xqliza/devops-training/applications/website/src/assets/configs

