apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-pv
  namespace: training-app-frontend-prod
  labels:
    type: local
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/zomita/Desktop/devops-training/devops-training/applications/website/src/assets/configs"
  storageClassName: local-storage