apiVersion: v1
kind: Secret
metadata:
  name: qr-secret
  namespace: training-app-backend-prod
type: Opaque
data:
  QR_TMP_FOLDER: "Li9nZW5lcmF0ZWRfcXI="
  QR_FILL_COLOR: "IzEyMTEyOA=="
  QR_BACKGROUND_COLOR: "I2RjZGJkYg=="
  USE_BUCKET: "dHJ1ZQ=="
  BUCKET_ENDPOINT: "cGxheS5taW4uaW86OTAwMA=="
  BUCKET_ACCESS_KEY: "UTNBTTNVUTg2N1NQUVFBNDNQMkY="
  BUCKET_SECRET_KEY: "enVmK3RmdGVTbHN3UnU3Qko4Nndla2l0bmlmSUxiWmFtMUtZWTNURw=="
  BUCKET_NAME: "dGVzdDEyMw=="
  BUCKET_PATH: ""