apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config
  namespace: {{ .Values.backendNamespace }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  APP_PORT: {{ .Values.config.appPort | quote }}
  QR_URL: {{ .Values.config.qrUrl | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-deployment
  namespace: {{ .Values.backendNamespace }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: backend
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: backend
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: {{ include "chart.fullname" . }}-config
        - secretRef:
            name: {{ include "chart.fullname" . }}-db-secret
        image: {{ .Values.deployment.backend.image.repository }}:{{ .Values.deployment.backend.image.tag }}
        name: backend
        ports:
        - containerPort: 3000
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-service
  namespace: {{ .Values.backendNamespace }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: backend
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.service.ports | toYaml | nindent 2 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}-ingress
  labels:
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
spec:
  rules:
  - host: app.backend.local
    http:
      paths:
      - backend:
          service:
            name: '{{ include "chart.fullname" . }}-service'
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - app.backend.local
  - secretName: tls-backend-secret