apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-db-secret
  namespace: {{ .Values.backendNamespace }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  MONGO_DB: {{ required "dbSecret.mongoDb is required" .Values.dbSecret.mongoDb |
    b64enc | quote }}
  MONGO_URI: {{ required "dbSecret.mongoUri is required" .Values.dbSecret.mongoUri
    | b64enc | quote }}
type: Opaque