apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.backendNamespace }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.frontendNamespace }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "2"