apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-tls-secret
  namespace: {{ .Values.backendNamespace }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  tls.crt: {{ required "tlsSecret.tlsCrt is required" .Values.tlsSecret.tlsCrt |
    b64enc | quote }}
  tls.key: {{ required "tlsSecret.tlsKey is required" .Values.tlsSecret.tlsKey |
    b64enc | quote }}
type: kubernetes.io/tls
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-tls-backend-secret
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  tls.crt: {{ required "tlsSecret.tlsCrt is required" .Values.tlsSecret.tlsCrt
    | b64enc | quote }}
  tls.key: {{ required "tlsSecret.tlsKey is required" .Values.tlsSecret.tlsKey
    | b64enc | quote }}
type: kubernetes.io/tls