apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: training-app-backend-prod
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.deployment.backend.image }}
        ports:
        - containerPort: {{ .Values.deployment.backend.port }}
        envFrom:
        - secretRef:
            name: backendsecret

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: training-app-backend-prod
spec:
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: {{ .Values.deployment.backend.port }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  labels:
    name: backend-ingress
  namespace: training-app-backend-prod
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
spec:
  tls:
  - hosts:
    - backend.com
    secretName: certificate-secret
  rules:
  - host: backend.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: backend-service
            port:
              number: 3000